import "./globals.css";
import type { Metadata } from "next";
import Modal from "../components/Modal";

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by sethmwebi",
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        <Modal />
        {children}
      </body>
    </html>
  );
}
